# Generated by Django 3.2 on 2021-10-03 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="personal", max_length=100)),
                ("tarif", models.CharField(default="personal", max_length=100)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                ("license_plate", models.CharField(max_length=16)),
                ("json_data", models.CharField(default="{}", max_length=1000)),
                ("iin", models.CharField(default="", max_length=12)),
                ("active", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("json_data", models.CharField(default="{}", max_length=1000)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="initiated", max_length=100)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.subscription",
                    ),
                ),
            ],
        ),
    ]
