# Generated by Django 3.2 on 2021-10-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
