# Generated by Django 3.2 on 2021-10-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211003_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
