# Generated by Django 3.2 on 2021-10-09 13:18

from django.db import migrations
from django.contrib.auth.models import User
from app.models import Profile


def create_superuser(apps, schema_editor):
    # if not User.objects.filter(username="87788620140").exists():
    #     user = User()
    #     user.username = "87788620140"
    #     user.set_password("timurtimur")
    #     user.email = "timurbakibayev@gmail.com"
    #     user.is_staff = True
    #     user.is_superuser = True
    #     user.save()
    #     profile = Profile()
    #     profile.user = user
    #     profile.save()

    # if not User.objects.filter(username="87789711555").exists():
    #     user = User()
    #     user.username = "87789711555"
    #     user.set_password("kuanyshkuanysh")
    #     user.email = "kuanqk@gmail.com"
    #     user.is_staff = True
    #     user.is_superuser = True
    #     user.save()
    #     profile = Profile()
    #     profile.user = user
    #     profile.save()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211009_1315'),
    ]

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop)
    ]
