# Generated by Django 3.2 on 2021-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211009_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_code',
            field=models.CharField(default='1233212', max_length=100),
        ),
    ]
