# Generated by Django 3.2 on 2021-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_sms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_ok',
            field=models.BooleanField(default=False),
        ),
    ]
