# Generated by Django 3.2.5 on 2021-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
    ]
