# Generated by Django 3.2 on 2021-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211016_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='url_to_pay',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
